name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # todos los días a medianoche
  workflow_dispatch:

permissions:
  contents: write   # 🔑 necesario para hacer push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: RCu3llar
          outputs: dist/snake.svg

      - name: Push snake animation to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

